--1. CREACION DE TABLAS

CREATE TABLE CLIENTE 
(
IDCLIENTE INTEGER NOT NULL,
RFC VARCHAR (13) NOT NULL,
NOMBRE VARCHAR (50),
APPATERNO VARCHAR (25),
APMATERNO VARCHAR (25),
CALLE VARCHAR (50),
NUMERO VARCHAR(10),
COLONIA VARCHAR(50),
CP VARCHAR(5),
MUNICIPIO VARCHAR(50),
LADA1 VARCHAR(5),
TELEFONO1 VARCHAR(10),
LADA2 VARCHAR(5),
TELEFONO2 VARCHAR(10),
SALDO DOUBLE NOT NULL,
PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PAGO 
(
IDPAGO INTEGER NOT NULL,
FECHA DATE NOT NULL,
PRIMARY KEY(IDPAGO)
);

CREATE TABLE FACTURA
(
IDFACTURA INTEGER NOT NULL,
FOLIO VARCHAR(9) NOT NULL,
FECHA DATE NOT NULL,
IVA DOUBLE NOT NULL,
IMPORTE DOUBLE NOT NULL,
TIPO_FACTURA VARCHAR(7) NOT NULL,
SALDO DOUBLE NOT NULL,
IDCLIENTE INTEGER NOT NULL,
IDPAGO INTEGER,
PRIMARY KEY (IDFACTURA),
FOREIGN KEY (IDCLIENTE) REFERENCES PROJECT.CLIENTE(IDCLIENTE),
FOREIGN KEY (IDPAGO) REFERENCES PROJECT.PAGO(IDPAGO)
);

CREATE TABLE GRUPO
(
IDGRUPO INTEGER NOT NULL,
NOMBRE VARCHAR(50),
LINEA VARCHAR(20),
UNIDAD VARCHAR(5) NOT NULL,
PRIMARY KEY (IDGRUPO)
);

CREATE TABLE ESTANDAR
(
IDESTANDAR INTEGER NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
PRIMARY KEY (IDESTANDAR)
);

CREATE TABLE MODELO
(
IDMODELO INTEGER NOT NULL,
NOMBRE VARCHAR(30),
FABRICANTE VARCHAR(30) NOT NULL,
PRIMARY KEY (IDMODELO)
);

CREATE TABLE AUTOMOVIL
(
IDAUTOMOVIL INTEGER NOT NULL,
IDMODELO INTEGER NOT NULL,
AÑO SMALLINT NOT NULL,
MOTOR VARCHAR(15) NOT NULL,
PRIMARY KEY (IDAUTOMOVIL),
FOREIGN KEY (IDMODELO) REFERENCES PROJECT.MODELO(IDMODELO)
);

CREATE TABLE AUTO_ESTANDAR
(
IDAUTOMOVIL INTEGER NOT NULL,
IDESTANDAR INTEGER NOT NULL,
PRIMARY KEY (IDAUTOMOVIL, IDESTANDAR),
FOREIGN KEY (IDAUTOMOVIL) REFERENCES PROJECT.AUTOMOVIL(IDAUTOMOVIL),
FOREIGN KEY (IDESTANDAR) REFERENCES PROJECT.ESTANDAR(IDESTANDAR)
);

CREATE TABLE PRODUCTO
(
IDPRODUCTO INTEGER NOT NULL,
IDGRUPO INTEGER NOT NULL,
MARCA VARCHAR(30) NOT NULL,
CLAVE_EXTERNA VARCHAR(20),
UBICACION VARCHAR(50),
PRECIO DOUBLE NOT NULL,
EXISTENCIAS INTEGER,
IDESTANDAR INTEGER,
PRIMARY KEY (IDPRODUCTO),
FOREIGN KEY (IDGRUPO) REFERENCES PROJECT.GRUPO(IDGRUPO),
FOREIGN KEY (IDESTANDAR) REFERENCES PROJECT.ESTANDAR(IDESTANDAR)
);

CREATE TABLE PROD_VENDIDO
(
IDFACTURA INTEGER NOT NULL,
IDPRODUCTO INTEGER NOT NULL,
PRECIO DOUBLE NOT NULL,
CANTIDAD INTEGER NOT NULL,
PRIMARY KEY (IDFACTURA, IDPRODUCTO),
FOREIGN KEY (IDFACTURA) REFERENCES PROJECT.FACTURA(IDFACTURA),
FOREIGN KEY (IDPRODUCTO) REFERENCES PROJECT.PRODUCTO(IDPRODUCTO)
);

CREATE TABLE PROVEEDOR
(
IDPROVEEDOR INTEGER NOT NULL,
RFC VARCHAR(13) NOT NULL,
NOMBRE VARCHAR (50),
APPATERNO VARCHAR (25),
APMATERNO VARCHAR (25),
CALLE VARCHAR (50),
NUMERO VARCHAR(10),
COLONIA VARCHAR(50),
REFERENCIAS VARCHAR(100),
CP VARCHAR(5),
MUNICIPIO VARCHAR(50),
LADA VARCHAR(5),
TELEFONO VARCHAR(10),
PRIMARY KEY (IDPROVEEDOR)
);

CREATE TABLE CONTACTO_PROVEEDOR
(
IDPROVEEDOR INTEGER NOT NULL,
IDCONTACTO INTEGER NOT NULL,
NOMBRE VARCHAR (50),
APPATERNO VARCHAR (25),
APMATERNO VARCHAR (25),
CARGO VARCHAR(50),
EXTENSION VARCHAR(8),
LADA2 VARCHAR(5),
TELEFONO2 VARCHAR(10),
PRIMARY KEY (IDPROVEEDOR, IDCONTACTO),
FOREIGN KEY (IDPROVEEDOR) REFERENCES PROJECT.PROVEEDOR(IDPROVEEDOR)
);

CREATE TABLE PEDIDO
(
IDPEDIDO INTEGER NOT NULL,
FECHA_PEDIDO DATE NOT NULL,
IMPORTE DOUBLE NOT NULL,
FECHA_RECIBIDO DATE,
IVA DOUBLE NOT NULL,
IDPROVEEDOR INTEGER NOT NULL,
PRIMARY KEY (IDPEDIDO),
FOREIGN KEY (IDPROVEEDOR) REFERENCES PROJECT.PROVEEDOR(IDPROVEEDOR)
);

CREATE TABLE PROD_PEDIDO
(
IDPRODUCTO INTEGER NOT NULL,
IDPEDIDO INTEGER NOT NULL,
COSTO DOUBLE,
CANTIDAD INTEGER NOT NULL,
PRIMARY KEY (IDPRODUCTO, IDPEDIDO),
FOREIGN KEY (IDPRODUCTO) REFERENCES PROJECT.PRODUCTO(IDPRODUCTO),
FOREIGN KEY (IDPEDIDO) REFERENCES PROJECT.PEDIDO(IDPEDIDO)
);

CREATE TABLE PROD_SURTIDO
(
IDPRODUCTO INTEGER NOT NULL,
IDPROVEEDOR INTEGER NOT NULL,
PRIMARY KEY (IDPRODUCTO, IDPROVEEDOR),
FOREIGN KEY (IDPRODUCTO) REFERENCES PROJECT.PRODUCTO(IDPRODUCTO),
FOREIGN KEY (IDPROVEEDOR) REFERENCES PROJECT.PROVEEDOR(IDPROVEEDOR)
);