--CREAR PEDIDO
INSERT INTO PROJECT.PEDIDO
(IDPEDIDO, FECHA_PEDIDO, IMPORTE, FECHA_RECIBIDO, IVA, IDPROVEEDOR)
VALUES(551, '2012-02-20-00.00.00.000000', 0, '2012-02-21-00.00.00.000000', 0,
(SELECT IDPROVEEDOR FROM PROVEEDOR p WHERE NOMBRE = 'PRO Europartes S.A. de C.V.'));
--SE HACE UN SUBQUERY PARA AVERIGUAR EL ID DE PRO EUROPARTES SA DE CV

--CREAR PRODUCTO PEDIDO
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(14944, 551, 5,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 14944) / 1.3);

INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(15185, 551, 2,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15185) / 1.3);

INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(13142, 551, 2,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 13142) / 1.3);

INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(16234, 551, 1,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 16234) / 1.3);

--DIVIDIMOS EL PRECIO ENTRE 1.3 PARA SACAR EL COSTO, YA QUE EL PRECIO ES 30% MÁS QUE EL COSTO

--COMPLETAR LOS VALORES DEL PEDIDO
UPDATE PEDIDO 
SET 
IMPORTE = (SELECT SUM(CANTIDAD*COSTO) FROM PROD_PEDIDO WHERE IDPEDIDO = 551) * 1.16,
IVA = (SELECT SUM(CANTIDAD*COSTO) FROM PROD_PEDIDO WHERE IDPEDIDO = 551) * 0.16
WHERE IDPEDIDO = 551;

--ACTUALIZAR EXISTENCIA
UPDATE PRODUCTO 
SET EXISTENCIAS = EXISTENCIAS + 5
WHERE IDPRODUCTO = 14944;

UPDATE PRODUCTO
SET EXISTENCIAS = EXISTENCIAS + 2
WHERE IDPRODUCTO IN (15185, 13142);

UPDATE PRODUCTO 
SET EXISTENCIAS = EXISTENCIAS + 1
WHERE IDPRODUCTO = 16234;
