--CREAR PEDIDO
INSERT INTO PROJECT.PEDIDO
(IDPEDIDO, FECHA_PEDIDO, IMPORTE, FECHA_RECIBIDO, IVA, IDPROVEEDOR)
VALUES(551, '2012-02-20-00.00.00.000000', 3436.38, '2012-02-21-00.00.00.000000', 473.98,
(SELECT IDPROVEEDOR FROM PROVEEDOR p WHERE NOMBRE = 'PRO Europartes S.A. de C.V.'));
--SE HACE UN SUBQUERY PARA AVERIGUAR EL ID DE PRO EUROPARTES SA DE CV

--REVISAR QUE SE HIZO BIEN LA INSERCIÓN
SELECT * FROM PEDIDO WHERE IDPEDIDO = 551;

--HACER UN SELECT PARA AVERIGUAR LOS ID DE PRODUCTO QUE NECESITO PARA CREAR PRODUCTO PEDIDO
SELECT *, (PRECIO / 1.3) AS COSTO FROM PRODUCTO p WHERE CLAVE_EXTERNA IN ('SET1', '5791', 'CA7351', '24');

--CREAR PRODUCTO PEDIDO
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(14944, 551, 5,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 14944) / 1.3);

INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(15185, 551, 2,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15185) / 1.3);

INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(13142, 551, 2,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 13142) / 1.3);

INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(16234, 551, 1,
(SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 16234) / 1.3);

--DIVIDIMOS EL PRECIO ENTRE 1.3 PARA SACAR EL COSTO, YA QUE EL PRECIO ES 30% MÁS QUE EL COSTO
--EN MI OPINIÓN, HACE FALTA UN CAMPO EN PRODUCTO QUE TENGA EL COSTO,
--PERO ES DEMASIADO TARDE PARA AGREGARLO Y NO ESTÁ EN EL DIAGRAMA ER SUGERIDO

--REVISAR QUE SE HAYAN INSERTADO CORRECTAMENTE
SELECT * FROM PROD_PEDIDO pp WHERE IDPEDIDO = 551;
