--INSERTAR EL PEDIDO 721 SIN RECIBIR
INSERT INTO PROJECT.PEDIDO
(IDPEDIDO, FECHA_PEDIDO, IMPORTE, FECHA_RECIBIDO, IVA, IDPROVEEDOR)
VALUES(721, '2012-02-25-00.00.00.000000', 0, NULL, 0, 3);

--INSERTAR LOS PRODUCTOS PEDIDOS

--INSERT PRODUCTO 1
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(15185, 721, 3, (SELECT PRECIO / 1.3 FROM PRODUCTO WHERE IDPRODUCTO = 15185));

--INSERT PRODUCTO 2
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(16234, 721, 4, (SELECT PRECIO / 1.3 FROM PRODUCTO WHERE IDPRODUCTO = 16234));

--INSERT PRODUCTO 3
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(18615, 721, 2, (SELECT PRECIO / 1.3 FROM PRODUCTO WHERE IDPRODUCTO = 18615));

--COMPLETAR LOS VALORES DEL PEDIDO
UPDATE PEDIDO 
SET 
IMPORTE = (SELECT SUM(CANTIDAD*COSTO) FROM PROD_PEDIDO WHERE IDPEDIDO = 721) * 1.16,
IVA = (SELECT SUM(CANTIDAD*COSTO) FROM PROD_PEDIDO WHERE IDPEDIDO = 721) * 0.16
WHERE IDPEDIDO = 721;
