--INSERTAR EL PEDIDO 728 SIN RECIBIR
INSERT INTO PROJECT.PEDIDO
(IDPEDIDO, FECHA_PEDIDO, IMPORTE, FECHA_RECIBIDO, IVA, IDPROVEEDOR)
VALUES(728, '2012-03-25-00.00.00.000000', 0, NULL, 0, 5);

--INSERTAR LOS PRODUCTOS PEDIDOS

--INSERT PRODUCTO 1
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(15926, 728, 3, (SELECT PRECIO / 1.3 FROM PRODUCTO WHERE IDPRODUCTO = 15926));

--INSERT PRODUCTO 2
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(20156, 728, 9, (SELECT PRECIO / 1.3 FROM PRODUCTO WHERE IDPRODUCTO = 20156));

--INSERT PRODUCTO 3
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(20614, 728, 5, (SELECT PRECIO / 1.3 FROM PRODUCTO WHERE IDPRODUCTO = 20614));

--COMPLETAR LOS VALORES DEL PEDIDO
UPDATE PEDIDO 
SET 
IMPORTE = (SELECT SUM(CANTIDAD*COSTO) FROM PROD_PEDIDO WHERE IDPEDIDO = 728) * 1.16,
IVA = (SELECT SUM(CANTIDAD*COSTO) FROM PROD_PEDIDO WHERE IDPEDIDO = 728) * 0.16
WHERE IDPEDIDO = 728;