--SELECT PARA IDENTIFICAR LOS PRODUCTOS QUE PUEDE SURTIR EL PROOVEDOR 1
SELECT p.IDPROVEEDOR, p.NOMBRE, ps.IDPRODUCTO AS SURTE_PRODUCTO FROM  PROVEEDOR p, PROD_SURTIDO ps
WHERE p.IDPROVEEDOR = ps.IDPROVEEDOR AND p.IDPROVEEDOR = 1;

--INSERTAR EL PEDIDO
INSERT INTO PROJECT.PEDIDO
(IDPEDIDO, FECHA_PEDIDO, IMPORTE, FECHA_RECIBIDO, IVA, IDPROVEEDOR)
VALUES(714, '2012-02-25-00.00.00.000000', 682.08, '2012-02-26-00.00.00.000000', 94.08, 1);

--REVISAR QUE SE INSERTO CORRECTAMENTE
SELECT * FROM PEDIDO WHERE IDPEDIDO = 714;

--INSERTAR LOS PRODUCTOS PEDIDOS

--SELECT PARA CALCULAR EL COSTO PRODUCTO 1
SELECT PRECIO, PRECIO / 1.3 AS COSTO FROM PRODUCTO WHERE IDPRODUCTO = 10164;

--INSERT PRODUCTO 1
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(10164, 714, 3, 52.5);

--SELECT PARA CALCULAR EL COSTO PRODUCTO 2
SELECT PRECIO, PRECIO / 1.3 AS COSTO FROM PRODUCTO WHERE IDPRODUCTO = 10658;

--INSERT PRODUCTO 2
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(10658, 714, 4, 42);

--SELECT PARA CALCULAR EL COSTO PRODUCTO 3
SELECT PRECIO, PRECIO / 1.3 AS COSTO FROM PRODUCTO WHERE IDPRODUCTO = 13111;

--INSERT PRODUCTO 3
INSERT INTO PROJECT.PROD_PEDIDO
(IDPRODUCTO, IDPEDIDO, CANTIDAD, COSTO)
VALUES(13111, 714, 5, 52.5);

--REVISAR QUE SE INSERTARON CORRECTAMENTE
SELECT * FROM PROD_PEDIDO pp WHERE IDPEDIDO = 714;
