--INSERTAR PAGO
INSERT INTO PROJECT.PAGO
(IDPAGO , FECHA )
VALUES
(5, '2012-02-16-19.34.00.000000');

--INSERTAR LA FACTURA
INSERT INTO PROJECT.FACTURA
(IDFACTURA, FOLIO, FECHA, IVA, IMPORTE, TIPO_FACTURA, SALDO, IDCLIENTE, IDPAGO)
VALUES(11, 'WABJ60168', '2012-02-16-19.34.00.000000', 0, 0, 'CREDITO', 0, 1, 5);

--INSERTAR PRODUCTOS VENDIDOS

--INSERTAR PRODUCTO VENDIDO 1
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(11, 15185, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15185) , 2);

--INSERTAR PRODUCTO VENDIDO 2
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(11, 15926, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15926), 2);

--INSERTAR PRODUCTO VENDIDO 3
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(11, 13142, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 13142) , 1);

--ACTUALIZAR EL IMPORTE Y EL IVA DE LA FACTURA BASADO EN LA SUMA DE LOS PRECIOS
UPDATE PROJECT.FACTURA
SET IVA=(SELECT SUM(PRECIO*CANTIDAD)* 0.16 FROM PROD_VENDIDO WHERE IDFACTURA = 11),
IMPORTE=(SELECT SUM(PRECIO*CANTIDAD)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 11)
WHERE IDFACTURA=11;

--ACTUALIZAR EXSTENCIAS
UPDATE PRODUCTO
SET
EXISTENCIAS = EXISTENCIAS - 2
WHERE IDPRODUCTO IN(15185, 15926) ;

UPDATE PRODUCTO 
SET 
EXISTENCIAS = EXISTENCIAS - 1
WHERE IDPRODUCTO = 13142;

