--INSERTAR PAGO
INSERT INTO PROJECT.PAGO
(IDPAGO , FECHA )
VALUES
(5, '2012-02-16-19.34.00.000000');

--INSERTAR LA FACTURA
INSERT INTO PROJECT.FACTURA
(IDFACTURA, FOLIO, FECHA, IVA, IMPORTE, TIPO_FACTURA, SALDO, IDCLIENTE, IDPAGO)
VALUES(11, 'WABJ60168', '2012-02-16-19.34.00.000000', 0, 0, 'CREDITO', 0, 1, 5);

--INSERTAR PRODUCTOS VENDIDOS
--SELECT PARA VER LOS POSIBLES PRODUCTOS
SELECT * FROM PRODUCTO p ;

--INSERTAR PRODUCTO VENDIDO 1
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(11, 15185, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15185) * 2, 2);

--INSERTAR PRODUCTO VENDIDO 2
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(11, 15926, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15926) * 2, 2);

--INSERTAR PRODUCTO VENDIDO 3
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(11, 13142, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 13142) , 1);

--ACTUALIZAR EL IMPORTE Y EL IVA DE LA FACTURA BASADO EN LA SUMA DE LOS PRECIOS
UPDATE PROJECT.FACTURA
SET IVA=(SELECT SUM(PRECIO)* 0.16 FROM PROD_VENDIDO WHERE IDFACTURA = 11),
IMPORTE=(SELECT SUM(PRECIO)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 11)
WHERE IDFACTURA=11;

--REVISAR QUE SE A?ADIO CORRECTAMENTE
SELECT * FROM FACTURA WHERE IDFACTURA = 11;

SELECT * FROM PROD_VENDIDO pv WHERE IDFACTURA = 11;
