--PROCESO PARA LA FACTURA WABJ59951
--INSERTAR EL PAGO PARA LA FACTURA
INSERT INTO PROJECT.PAGO
(IDPAGO, FECHA)
VALUES(0, '2012-03-12');

--INSERTAR LA FACTURA
INSERT INTO PROJECT.FACTURA
(IDFACTURA, FOLIO, FECHA, IVA, IMPORTE, TIPO_FACTURA, SALDO, IDCLIENTE, IDPAGO)
VALUES(1, 'WABJ59951', '2012-03-12', 0, 0, 'CONTADO', 0, 2, 0);

--INSERTAR PRODUCTOS VENDIDOS

--INSERTAR PRODUCTO VENDIDO 1
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(1, 17909, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 17909) , 3);

--INSERTAR PRODUCTO VENDIDO 2
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(1, 20614, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 20614) , 5);

--INSERTAR PRODUCTO VENDIDO 3
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(1, 13142, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 13142) , 4);

--ACTUALIZAR EL IMPORTE Y EL IVA DE LA FACTURA BASADO EN LA SUMA DE LOS PRECIOS
UPDATE PROJECT.FACTURA
SET IVA=(SELECT SUM(PRECIO*CANTIDAD)* 0.16 FROM PROD_VENDIDO WHERE IDFACTURA = 1),
IMPORTE=(SELECT SUM(PRECIO*CANTIDAD)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 1)
WHERE IDFACTURA=1;

--ACTUALIZAR EXSTENCIAS
UPDATE PRODUCTO
SET
EXISTENCIAS = EXISTENCIAS - 3
WHERE IDPRODUCTO = 17909;

UPDATE PRODUCTO 
SET 
EXISTENCIAS = EXISTENCIAS - 5
WHERE IDPRODUCTO = 20614;

UPDATE PRODUCTO 
SET 
EXISTENCIAS = EXISTENCIAS - 4
WHERE IDPRODUCTO = 13142;



