--SELECT PARA VER LOS POSIBLES CLIENTES
SELECT * FROM PROJECT.CLIENTE ;

--INSERTAR LA FACTURA
INSERT INTO PROJECT.FACTURA
(IDFACTURA, FOLIO, FECHA, IVA, IMPORTE, TIPO_FACTURA, SALDO, IDCLIENTE, IDPAGO)
VALUES(9, 'WABJ59949', '2012-03-18', 0, 0, 'CREDITO', 0, 9, NULL);

--INSERTAR PRODUCTOS VENDIDOS
--SELECT PARA VER LOS POSIBLES PRODUCTOS
SELECT * FROM PRODUCTO p ;

--INSERTAR PRODUCTO VENDIDO 1
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(9, 10471, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 10471) * 3, 3);

--INSERTAR PRODUCTO VENDIDO 2
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(9, 13111, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 13111) * 5, 5);

--INSERTAR PRODUCTO VENDIDO 3
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(9, 19585, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 19585) * 4, 4);

--ACTUALIZAR EL IMPORTE Y EL IVA DE LA FACTURA BASADO EN LA SUMA DE LOS PRECIOS
UPDATE PROJECT.FACTURA
SET IVA=(SELECT SUM(PRECIO)* 0.16 FROM PROD_VENDIDO WHERE IDFACTURA = 9),
IMPORTE=(SELECT SUM(PRECIO)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 9),
SALDO=(SELECT SUM(PRECIO)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 9)
WHERE IDFACTURA=9;

--REVISAR QUE SE A?ADIO CORRECTAMENTE
SELECT * FROM FACTURA WHERE IDFACTURA = 9;

SELECT * FROM PROD_VENDIDO pv WHERE IDFACTURA = 9;






