--PROCESO DE LA FACTURA WABJ59946
--INSERTAR LA FACTURA
INSERT INTO PROJECT.FACTURA
(IDFACTURA, FOLIO, FECHA, IVA, IMPORTE, TIPO_FACTURA, SALDO, IDCLIENTE, IDPAGO)
VALUES(7, 'WABJ59946', '2012-03-17', 0, 0, 'CREDITO', 0, 7, NULL);

--INSERTAR PRODUCTOS VENDIDOS

--INSERTAR PRODUCTO VENDIDO 1
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(7, 18615, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 18615), 3);

--INSERTAR PRODUCTO VENDIDO 2
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(7, 14944, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 14944), 5);

--INSERTAR PRODUCTO VENDIDO 3
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(7, 15920, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15920), 4);

--ACTUALIZAR EL IMPORTE Y EL IVA DE LA FACTURA BASADO EN LA SUMA DE LOS PRECIOS
UPDATE PROJECT.FACTURA
SET IVA=(SELECT SUM(PRECIO*CANTIDAD)* 0.16 FROM PROD_VENDIDO WHERE IDFACTURA = 7),
IMPORTE=(SELECT SUM(PRECIO*CANTIDAD)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 7),
SALDO=(SELECT SUM(PRECIO*CANTIDAD)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 7)
WHERE IDFACTURA=7;

--ACTUALIZAR EXSTENCIAS
UPDATE PRODUCTO
SET
EXISTENCIAS = EXISTENCIAS - 3
WHERE IDPRODUCTO = 18615;

UPDATE PRODUCTO 
SET 
EXISTENCIAS = EXISTENCIAS - 5
WHERE IDPRODUCTO = 14944;

UPDATE PRODUCTO 
SET 
EXISTENCIAS = EXISTENCIAS - 4
WHERE IDPRODUCTO = 15920;
