--PROCESO PARA LA FACTURA WABJ59952
--INSERTAR EL PAGO PARA LA FACTURA
INSERT INTO PROJECT.PAGO
(IDPAGO, FECHA)
VALUES(1, '2012-03-13');

--INSERTAR LA FACTURA
INSERT INTO PROJECT.FACTURA
(IDFACTURA, FOLIO, FECHA, IVA, IMPORTE, TIPO_FACTURA, SALDO, IDCLIENTE, IDPAGO)
VALUES(2, 'WABJ59952', '2012-03-13', 0, 0, 'CONTADO', 0, 3, 1);

--INSERTAR PRODUCTOS VENDIDOS

--INSERTAR PRODUCTO VENDIDO 1
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(2, 16234, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 16234), 3);

--INSERTAR PRODUCTO VENDIDO 2
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(2, 18615, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 18615), 5);

--INSERTAR PRODUCTO VENDIDO 3
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(2, 10164, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 10164), 4);

--ACTUALIZAR EL IMPORTE Y EL IVA DE LA FACTURA BASADO EN LA SUMA DE LOS PRECIOS
UPDATE PROJECT.FACTURA
SET IVA=(SELECT SUM(PRECIO*CANTIDAD)* 0.16 FROM PROD_VENDIDO WHERE IDFACTURA = 2),
IMPORTE=(SELECT SUM(PRECIO*CANTIDAD)* 1.16 FROM PROD_VENDIDO WHERE IDFACTURA = 2)
WHERE IDFACTURA=2;

--ACTUALIZAR EXSTENCIAS
UPDATE PRODUCTO
SET
EXISTENCIAS = EXISTENCIAS - 3
WHERE IDPRODUCTO = 16234;

UPDATE PRODUCTO 
SET 
EXISTENCIAS = EXISTENCIAS - 5
WHERE IDPRODUCTO = 18615;

UPDATE PRODUCTO 
SET 
EXISTENCIAS = EXISTENCIAS - 4
WHERE IDPRODUCTO = 10164;
