-- CREAR LA FACTURA
INSERT INTO PROJECT.FACTURA
(IDFACTURA, FOLIO, FECHA, IVA, IMPORTE, TIPO_FACTURA, SALDO, IDCLIENTE, IDPAGO)
VALUES
(0, 'WABJ59909', '2012-02-16-19.34.00.000000', 509.02, 3690.38, 'CREDITO', 3690.38, 
(SELECT IDCLIENTE FROM CLIENTE WHERE NOMBRE = 'ITESO'), NULL);
--SE UTILIZA UN SUB-QUERY PARA AVERIGUAR EL IDCLIENTE DE ITESO

--CHECAR QUE SE CREO CORRECTAMENTE
SELECT * FROM FACTURA f WHERE IDFACTURA = 0;

--BORRAR EN CASO DE QUE NO SE HAYA CREADO CORRECTAMENTE
DELETE FROM PROJECT.FACTURA
WHERE IDFACTURA=0;

--INSERTAR LOS PRODUCTOS VENDIDOS EN LA FACTURA
INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(0, 15185, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15185)* 2 , 2);

INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(0, 15926, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 15926)* 2 , 2);

INSERT INTO PROJECT.PROD_VENDIDO
(IDFACTURA, IDPRODUCTO, PRECIO, CANTIDAD)
VALUES(0, 13142, (SELECT PRECIO FROM PRODUCTO WHERE IDPRODUCTO = 13142), 1);

--CHECAR QUE SE INSERTARON CORRECTAMENTE
SELECT * FROM PROD_VENDIDO pv WHERE IDFACTURA = 0;

