--INSERTAR PAGO
INSERT INTO PAGO
(IDPAGO, FECHA)
VALUES
((SELECT MAX(IDPAGO) FROM PAGO) + 1, '2012-04-18');

--LIQUIDAR LAS FACTURAS
UPDATE FACTURA
SET IDPAGO = (SELECT MAX(IDPAGO) FROM PAGO),
SALDO = 0
WHERE FOLIO IN ('WABJ59909', 'WABJ59946');